# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "rp-draft-app"
client_id = "4050657df080fdc5072b20712bd3e1cd"
application_url = "https://varieties-ensure-copies-commissions.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://varieties-ensure-copies-commissions.trycloudflare.com/auth/callback",
  "https://varieties-ensure-copies-commissions.trycloudflare.com/auth/shopify/callback",
  "https://varieties-ensure-copies-commissions.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "rpdmrishabh.myshopify.com"
